# Navigation menu
menu:
#  - name: Home
#    url: /
  - name: Archives
    url: /archives
#  - name: Categories
#    url: /categories
  - name: Tags
    url: /tags
  - name: About
    url: /about
#    # Open in new tab
#    target: _blank

site:
  favicon: /favicon.svg
  # Whether to display the seal (stamp) in the header
  seal: true
  rss:
    enabled: true
    path: /atom.xml
  github:
    enabled: true
    url: https://github.com/ObsisMc

# Analytics
analytics:
  # Only support Google Analytics 4
  google:
    enabled: false
    id: ""

# Comment systems
comments:
  enabled: false
  provider: disqus
  disqus:
    shortname: ""

# Excerpt settings
excerpt:
  fallback:
    enabled: true
    length: 200